# Generated by Django 5.0.2 on 2024-10-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='direct',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='overv',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runt',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Ex. Al Pacino', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='gross',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.CharField(default='Movie Overview', max_length=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='stara',
            field=models.CharField(default='ex. Robert Pattinson', max_length=300),
        ),
        migrations.AddField(
            model_name='movie',
            name='starb',
            field=models.CharField(default='ex. Robert Downey Jr.', max_length=300),
        ),
        migrations.AddField(
            model_name='movie',
            name='starc',
            field=models.CharField(default='ex. Robert de Niro', max_length=300),
        ),
        migrations.AddField(
            model_name='movie',
            name='stard',
            field=models.CharField(default='ex. Robert Cruz', max_length=300),
        ),
        migrations.AddField(
            model_name='movie',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cert',
            field=models.CharField(default='Movie Certificates', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Movie genres', max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default='Movie name', max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=1900),
        ),
    ]
