# Generated by Django 5.0.1 on 2024-12-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0002_alter_movie_cert_alter_movie_director_and_more'),
        ('finalproject', '0002_remove_movie_direct_remove_movie_overv_and_more'),
    ]

    operations = [
    ]
