# Generated by Django 5.0.2 on 2024-12-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0002_alter_movie_cert_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='match',
            field=models.IntegerField(default=0),
        ),
    ]
