# Generated by Django 5.0.1 on 2024-12-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0003_merge_20241201_1330'),
        ('finalproject', '0003_movie_match'),
    ]

    operations = [
    ]
